apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: fen5agvv2-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/fen5agvv2-java-quarkus-gitops